var wms_layers = [];


        var lyr_GSatelite_0 = new ol.layer.Tile({
            'title': 'GSatelite',
            'opacity': 1.000000,
            
            
            source: new ol.source.XYZ({
            attributions: ' ',
                url: 'http://www.google.cn/maps/vt?lyrs=s@189&gl=cn&x={x}&y={y}&z={z}'
            })
        });
var format_Linked_PSU_EA_Metro1_1 = new ol.format.GeoJSON();
var features_Linked_PSU_EA_Metro1_1 = format_Linked_PSU_EA_Metro1_1.readFeatures(json_Linked_PSU_EA_Metro1_1, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Linked_PSU_EA_Metro1_1 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Linked_PSU_EA_Metro1_1.addFeatures(features_Linked_PSU_EA_Metro1_1);
var lyr_Linked_PSU_EA_Metro1_1 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Linked_PSU_EA_Metro1_1, 
                style: style_Linked_PSU_EA_Metro1_1,
                popuplayertitle: "Linked_PSU_EA_Metro1",
                interactive: true,
                title: '<img src="styles/legend/Linked_PSU_EA_Metro1_1.png" /> Linked_PSU_EA_Metro1'
            });
var format_Linked_PSU_EA_Metro2_2 = new ol.format.GeoJSON();
var features_Linked_PSU_EA_Metro2_2 = format_Linked_PSU_EA_Metro2_2.readFeatures(json_Linked_PSU_EA_Metro2_2, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Linked_PSU_EA_Metro2_2 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Linked_PSU_EA_Metro2_2.addFeatures(features_Linked_PSU_EA_Metro2_2);
var lyr_Linked_PSU_EA_Metro2_2 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Linked_PSU_EA_Metro2_2, 
                style: style_Linked_PSU_EA_Metro2_2,
                popuplayertitle: "Linked_PSU_EA_Metro2",
                interactive: true,
                title: '<img src="styles/legend/Linked_PSU_EA_Metro2_2.png" /> Linked_PSU_EA_Metro2'
            });
var format_LPOs_Supervisors_Cape_Metro_3 = new ol.format.GeoJSON();
var features_LPOs_Supervisors_Cape_Metro_3 = format_LPOs_Supervisors_Cape_Metro_3.readFeatures(json_LPOs_Supervisors_Cape_Metro_3, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_LPOs_Supervisors_Cape_Metro_3 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_LPOs_Supervisors_Cape_Metro_3.addFeatures(features_LPOs_Supervisors_Cape_Metro_3);
var lyr_LPOs_Supervisors_Cape_Metro_3 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_LPOs_Supervisors_Cape_Metro_3, 
                style: style_LPOs_Supervisors_Cape_Metro_3,
                popuplayertitle: "LPOs_Supervisors_Cape_Metro",
                interactive: true,
                title: '<img src="styles/legend/LPOs_Supervisors_Cape_Metro_3.png" /> LPOs_Supervisors_Cape_Metro'
            });
var format_Metro_Split_Final_4 = new ol.format.GeoJSON();
var features_Metro_Split_Final_4 = format_Metro_Split_Final_4.readFeatures(json_Metro_Split_Final_4, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Metro_Split_Final_4 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Metro_Split_Final_4.addFeatures(features_Metro_Split_Final_4);
var lyr_Metro_Split_Final_4 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Metro_Split_Final_4, 
                style: style_Metro_Split_Final_4,
                popuplayertitle: "Metro_Split_Final",
                interactive: true,
                title: '<img src="styles/legend/Metro_Split_Final_4.png" /> Metro_Split_Final'
            });

lyr_GSatelite_0.setVisible(true);lyr_Linked_PSU_EA_Metro1_1.setVisible(true);lyr_Linked_PSU_EA_Metro2_2.setVisible(true);lyr_LPOs_Supervisors_Cape_Metro_3.setVisible(true);lyr_Metro_Split_Final_4.setVisible(true);
var layersList = [lyr_GSatelite_0,lyr_Linked_PSU_EA_Metro1_1,lyr_Linked_PSU_EA_Metro2_2,lyr_LPOs_Supervisors_Cape_Metro_3,lyr_Metro_Split_Final_4];
lyr_Linked_PSU_EA_Metro1_1.set('fieldAliases', {'OBJECTID': 'OBJECTID', 'PSU_NO_M': 'PSU_NO_M', 'EA_CODE': 'EA_CODE', 'EA_GTYPE': 'EA_GTYPE', 'EA_TYPE': 'EA_TYPE', 'SUB_EA_NR': 'SUB_EA_NR', 'SUB_EA_COD': 'SUB_EA_COD', 'SUB_EA_G_T': 'SUB_EA_G_T', 'SUB_EA_TYP': 'SUB_EA_TYP', 'DU_COUNT': 'DU_COUNT', 'DU_STATUS': 'DU_STATUS', 'FIELDWORKE': 'FIELDWORKE', 'FIELDWOR_1': 'FIELDWOR_1', 'SUPERVISOR': 'SUPERVISOR', 'SUPERVIS_1': 'SUPERVIS_1', 'FOO_NR': 'FOO_NR', 'FOO': 'FOO', 'MONITOR_NR': 'MONITOR_NR', 'MONITOR': 'MONITOR', 'ALTERNATE': 'ALTERNATE', 'EA_2011': 'EA_2011', 'SP_CODE': 'SP_CODE', 'SAL_CODE': 'SAL_CODE', 'GEO_ASSESS': 'GEO_ASSESS', 'GEO_POINT_': 'GEO_POINT_', 'FILTER_UPD': 'FILTER_UPD', 'FILTER_PRO': 'FILTER_PRO', 'EDITOR': 'EDITOR', 'EDITOR_STA': 'EDITOR_STA', 'QA_ASSURER': 'QA_ASSURER', 'QA_STATUS': 'QA_STATUS', 'QA_ASSUR_1': 'QA_ASSUR_1', 'QA_STATUS2': 'QA_STATUS2', 'created_us': 'created_us', 'created_da': 'created_da', 'last_edite': 'last_edite', 'last_edi_1': 'last_edi_1', 'SP_NAME': 'SP_NAME', 'MP_CODE': 'MP_CODE', 'MP_NAME': 'MP_NAME', 'MN_MDB_C': 'MN_MDB_C', 'MN_CODE': 'MN_CODE', 'MN_NAME': 'MN_NAME', 'MN_TYPE': 'MN_TYPE', 'DC_MDB_C': 'DC_MDB_C', 'DC_MN_C': 'DC_MN_C', 'DC_NAME': 'DC_NAME', 'PR_MDB_C': 'PR_MDB_C', 'PR_CODE': 'PR_CODE', 'PR_NAME': 'PR_NAME', 'GlobalID': 'GlobalID', 'ESTIMATED_': 'ESTIMATED_', 'OBSERVED_D': 'OBSERVED_D', 'QA_DU_COUN': 'QA_DU_COUN', 'MRN_COUNT': 'MRN_COUNT', 'HH_COUNT': 'HH_COUNT', 'SDI_COUNT': 'SDI_COUNT', 'GATED_COMM': 'GATED_COMM', 'OTHER': 'OTHER', 'PSU_STATUS': 'PSU_STATUS', 'COMMENTS': 'COMMENTS', 'COMMENTS2': 'COMMENTS2', 'HH_COUNT_2': 'HH_COUNT_2', 'DU_COUNT_2': 'DU_COUNT_2', 'EA_COUNT': 'EA_COUNT', 'MERGED_EA_': 'MERGED_EA_', 'Shape_Leng': 'Shape_Leng', 'Shape_Area': 'Shape_Area', 'EA': 'EA', 'PSUNO': 'PSUNO', 'rotation': 'rotation', 'EA_GTYPE_1': 'EA_GTYPE_1', 'EA_TYPE_1': 'EA_TYPE_1', 'SP_CODE_1': 'SP_CODE_1', 'SP_NAME_1': 'SP_NAME_1', 'MP_NAME_1': 'MP_NAME_1', 'MN_NAME_1': 'MN_NAME_1', 'DC_MDB_C_1': 'DC_MDB_C_1', 'DC_NAME_1': 'DC_NAME_1', 'PR_NAME_1': 'PR_NAME_1', 'PR_CODE_1': 'PR_CODE_1', 'STRATUM': 'STRATUM', 'EA2': 'EA2', 'PSU_NO_M_1': 'PSU_NO_M_1', 'EA_1': 'EA_1', 'MP_CODE_1': 'MP_CODE_1', 'EA_GTYPE_C': 'EA_GTYPE_C', 'EA_TYPE_C': 'EA_TYPE_C', 'MN_CODE_1': 'MN_CODE_1', 'DC_MN_C_1': 'DC_MN_C_1', });
lyr_Linked_PSU_EA_Metro2_2.set('fieldAliases', {'OBJECTID': 'OBJECTID', 'PSU_NO_M': 'PSU_NO_M', 'EA_CODE': 'EA_CODE', 'EA_GTYPE': 'EA_GTYPE', 'EA_TYPE': 'EA_TYPE', 'SUB_EA_NR': 'SUB_EA_NR', 'SUB_EA_COD': 'SUB_EA_COD', 'SUB_EA_G_T': 'SUB_EA_G_T', 'SUB_EA_TYP': 'SUB_EA_TYP', 'DU_COUNT': 'DU_COUNT', 'DU_STATUS': 'DU_STATUS', 'FIELDWORKE': 'FIELDWORKE', 'FIELDWOR_1': 'FIELDWOR_1', 'SUPERVISOR': 'SUPERVISOR', 'SUPERVIS_1': 'SUPERVIS_1', 'FOO_NR': 'FOO_NR', 'FOO': 'FOO', 'MONITOR_NR': 'MONITOR_NR', 'MONITOR': 'MONITOR', 'ALTERNATE': 'ALTERNATE', 'EA_2011': 'EA_2011', 'SP_CODE': 'SP_CODE', 'SAL_CODE': 'SAL_CODE', 'GEO_ASSESS': 'GEO_ASSESS', 'GEO_POINT_': 'GEO_POINT_', 'FILTER_UPD': 'FILTER_UPD', 'FILTER_PRO': 'FILTER_PRO', 'EDITOR': 'EDITOR', 'EDITOR_STA': 'EDITOR_STA', 'QA_ASSURER': 'QA_ASSURER', 'QA_STATUS': 'QA_STATUS', 'QA_ASSUR_1': 'QA_ASSUR_1', 'QA_STATUS2': 'QA_STATUS2', 'created_us': 'created_us', 'created_da': 'created_da', 'last_edite': 'last_edite', 'last_edi_1': 'last_edi_1', 'SP_NAME': 'SP_NAME', 'MP_CODE': 'MP_CODE', 'MP_NAME': 'MP_NAME', 'MN_MDB_C': 'MN_MDB_C', 'MN_CODE': 'MN_CODE', 'MN_NAME': 'MN_NAME', 'MN_TYPE': 'MN_TYPE', 'DC_MDB_C': 'DC_MDB_C', 'DC_MN_C': 'DC_MN_C', 'DC_NAME': 'DC_NAME', 'PR_MDB_C': 'PR_MDB_C', 'PR_CODE': 'PR_CODE', 'PR_NAME': 'PR_NAME', 'GlobalID': 'GlobalID', 'ESTIMATED_': 'ESTIMATED_', 'OBSERVED_D': 'OBSERVED_D', 'QA_DU_COUN': 'QA_DU_COUN', 'MRN_COUNT': 'MRN_COUNT', 'HH_COUNT': 'HH_COUNT', 'SDI_COUNT': 'SDI_COUNT', 'GATED_COMM': 'GATED_COMM', 'OTHER': 'OTHER', 'PSU_STATUS': 'PSU_STATUS', 'COMMENTS': 'COMMENTS', 'COMMENTS2': 'COMMENTS2', 'HH_COUNT_2': 'HH_COUNT_2', 'DU_COUNT_2': 'DU_COUNT_2', 'EA_COUNT': 'EA_COUNT', 'MERGED_EA_': 'MERGED_EA_', 'Shape_Leng': 'Shape_Leng', 'Shape_Area': 'Shape_Area', 'EA': 'EA', 'PSUNO': 'PSUNO', 'rotation': 'rotation', 'EA_GTYPE_1': 'EA_GTYPE_1', 'EA_TYPE_1': 'EA_TYPE_1', 'SP_CODE_1': 'SP_CODE_1', 'SP_NAME_1': 'SP_NAME_1', 'MP_NAME_1': 'MP_NAME_1', 'MN_NAME_1': 'MN_NAME_1', 'DC_MDB_C_1': 'DC_MDB_C_1', 'DC_NAME_1': 'DC_NAME_1', 'PR_NAME_1': 'PR_NAME_1', 'PR_CODE_1': 'PR_CODE_1', 'STRATUM': 'STRATUM', 'EA2': 'EA2', 'PSU_NO_M_1': 'PSU_NO_M_1', 'EA_1': 'EA_1', 'MP_CODE_1': 'MP_CODE_1', 'EA_GTYPE_C': 'EA_GTYPE_C', 'EA_TYPE_C': 'EA_TYPE_C', 'MN_CODE_1': 'MN_CODE_1', 'DC_MN_C_1': 'DC_MN_C_1', });
lyr_LPOs_Supervisors_Cape_Metro_3.set('fieldAliases', {'No': 'No', 'First_Name': 'First_Name', 'Surname': 'Surname', 'Gender': 'Gender', 'ID_Number': 'ID_Number', 'District': 'District', 'Province': 'Province', 'Position': 'Position', 'Address': 'Address', 'Contact_no': 'Contact_no', 'Latitude': 'Latitude', 'Longitude': 'Longitude', 'Latitude_D': 'Latitude_D', 'Longitude_': 'Longitude_', });
lyr_Metro_Split_Final_4.set('fieldAliases', {'OBJECTID': 'OBJECTID', 'DISTRICT': 'DISTRICT', 'DC_NAME': 'DC_NAME', 'Office': 'Office', });
lyr_Linked_PSU_EA_Metro1_1.set('fieldImages', {'OBJECTID': 'TextEdit', 'PSU_NO_M': 'TextEdit', 'EA_CODE': 'TextEdit', 'EA_GTYPE': 'TextEdit', 'EA_TYPE': 'TextEdit', 'SUB_EA_NR': 'TextEdit', 'SUB_EA_COD': 'TextEdit', 'SUB_EA_G_T': 'TextEdit', 'SUB_EA_TYP': 'TextEdit', 'DU_COUNT': 'TextEdit', 'DU_STATUS': 'TextEdit', 'FIELDWORKE': 'TextEdit', 'FIELDWOR_1': 'TextEdit', 'SUPERVISOR': 'TextEdit', 'SUPERVIS_1': 'TextEdit', 'FOO_NR': 'TextEdit', 'FOO': 'TextEdit', 'MONITOR_NR': 'TextEdit', 'MONITOR': 'TextEdit', 'ALTERNATE': 'TextEdit', 'EA_2011': 'TextEdit', 'SP_CODE': 'TextEdit', 'SAL_CODE': 'TextEdit', 'GEO_ASSESS': 'TextEdit', 'GEO_POINT_': 'TextEdit', 'FILTER_UPD': 'TextEdit', 'FILTER_PRO': 'TextEdit', 'EDITOR': 'TextEdit', 'EDITOR_STA': 'TextEdit', 'QA_ASSURER': 'TextEdit', 'QA_STATUS': 'TextEdit', 'QA_ASSUR_1': 'TextEdit', 'QA_STATUS2': 'TextEdit', 'created_us': 'TextEdit', 'created_da': 'DateTime', 'last_edite': 'TextEdit', 'last_edi_1': 'DateTime', 'SP_NAME': 'TextEdit', 'MP_CODE': 'TextEdit', 'MP_NAME': 'TextEdit', 'MN_MDB_C': 'TextEdit', 'MN_CODE': 'TextEdit', 'MN_NAME': 'TextEdit', 'MN_TYPE': 'TextEdit', 'DC_MDB_C': 'TextEdit', 'DC_MN_C': 'TextEdit', 'DC_NAME': 'TextEdit', 'PR_MDB_C': 'TextEdit', 'PR_CODE': 'TextEdit', 'PR_NAME': 'TextEdit', 'GlobalID': 'TextEdit', 'ESTIMATED_': 'TextEdit', 'OBSERVED_D': 'TextEdit', 'QA_DU_COUN': 'TextEdit', 'MRN_COUNT': 'TextEdit', 'HH_COUNT': 'TextEdit', 'SDI_COUNT': 'TextEdit', 'GATED_COMM': 'TextEdit', 'OTHER': 'TextEdit', 'PSU_STATUS': 'TextEdit', 'COMMENTS': 'TextEdit', 'COMMENTS2': 'TextEdit', 'HH_COUNT_2': 'TextEdit', 'DU_COUNT_2': 'TextEdit', 'EA_COUNT': 'TextEdit', 'MERGED_EA_': 'TextEdit', 'Shape_Leng': 'TextEdit', 'Shape_Area': 'TextEdit', 'EA': 'TextEdit', 'PSUNO': 'TextEdit', 'rotation': 'TextEdit', 'EA_GTYPE_1': 'TextEdit', 'EA_TYPE_1': 'TextEdit', 'SP_CODE_1': 'TextEdit', 'SP_NAME_1': 'TextEdit', 'MP_NAME_1': 'TextEdit', 'MN_NAME_1': 'TextEdit', 'DC_MDB_C_1': 'TextEdit', 'DC_NAME_1': 'TextEdit', 'PR_NAME_1': 'TextEdit', 'PR_CODE_1': 'TextEdit', 'STRATUM': 'TextEdit', 'EA2': 'TextEdit', 'PSU_NO_M_1': 'TextEdit', 'EA_1': 'TextEdit', 'MP_CODE_1': 'TextEdit', 'EA_GTYPE_C': 'TextEdit', 'EA_TYPE_C': 'TextEdit', 'MN_CODE_1': 'TextEdit', 'DC_MN_C_1': 'TextEdit', });
lyr_Linked_PSU_EA_Metro2_2.set('fieldImages', {'OBJECTID': 'TextEdit', 'PSU_NO_M': 'TextEdit', 'EA_CODE': 'TextEdit', 'EA_GTYPE': 'TextEdit', 'EA_TYPE': 'TextEdit', 'SUB_EA_NR': 'TextEdit', 'SUB_EA_COD': 'TextEdit', 'SUB_EA_G_T': 'TextEdit', 'SUB_EA_TYP': 'TextEdit', 'DU_COUNT': 'TextEdit', 'DU_STATUS': 'TextEdit', 'FIELDWORKE': 'TextEdit', 'FIELDWOR_1': 'TextEdit', 'SUPERVISOR': 'TextEdit', 'SUPERVIS_1': 'TextEdit', 'FOO_NR': 'TextEdit', 'FOO': 'TextEdit', 'MONITOR_NR': 'TextEdit', 'MONITOR': 'TextEdit', 'ALTERNATE': 'TextEdit', 'EA_2011': 'TextEdit', 'SP_CODE': 'TextEdit', 'SAL_CODE': 'TextEdit', 'GEO_ASSESS': 'TextEdit', 'GEO_POINT_': 'TextEdit', 'FILTER_UPD': 'TextEdit', 'FILTER_PRO': 'TextEdit', 'EDITOR': 'TextEdit', 'EDITOR_STA': 'TextEdit', 'QA_ASSURER': 'TextEdit', 'QA_STATUS': 'TextEdit', 'QA_ASSUR_1': 'TextEdit', 'QA_STATUS2': 'TextEdit', 'created_us': 'TextEdit', 'created_da': 'DateTime', 'last_edite': 'TextEdit', 'last_edi_1': 'DateTime', 'SP_NAME': 'TextEdit', 'MP_CODE': 'TextEdit', 'MP_NAME': 'TextEdit', 'MN_MDB_C': 'TextEdit', 'MN_CODE': 'TextEdit', 'MN_NAME': 'TextEdit', 'MN_TYPE': 'TextEdit', 'DC_MDB_C': 'TextEdit', 'DC_MN_C': 'TextEdit', 'DC_NAME': 'TextEdit', 'PR_MDB_C': 'TextEdit', 'PR_CODE': 'TextEdit', 'PR_NAME': 'TextEdit', 'GlobalID': 'TextEdit', 'ESTIMATED_': 'TextEdit', 'OBSERVED_D': 'TextEdit', 'QA_DU_COUN': 'TextEdit', 'MRN_COUNT': 'TextEdit', 'HH_COUNT': 'TextEdit', 'SDI_COUNT': 'TextEdit', 'GATED_COMM': 'TextEdit', 'OTHER': 'TextEdit', 'PSU_STATUS': 'TextEdit', 'COMMENTS': 'TextEdit', 'COMMENTS2': 'TextEdit', 'HH_COUNT_2': 'TextEdit', 'DU_COUNT_2': 'TextEdit', 'EA_COUNT': 'TextEdit', 'MERGED_EA_': 'TextEdit', 'Shape_Leng': 'TextEdit', 'Shape_Area': 'TextEdit', 'EA': 'TextEdit', 'PSUNO': 'TextEdit', 'rotation': 'TextEdit', 'EA_GTYPE_1': 'TextEdit', 'EA_TYPE_1': 'TextEdit', 'SP_CODE_1': 'TextEdit', 'SP_NAME_1': 'TextEdit', 'MP_NAME_1': 'TextEdit', 'MN_NAME_1': 'TextEdit', 'DC_MDB_C_1': 'TextEdit', 'DC_NAME_1': 'TextEdit', 'PR_NAME_1': 'TextEdit', 'PR_CODE_1': 'TextEdit', 'STRATUM': 'TextEdit', 'EA2': 'TextEdit', 'PSU_NO_M_1': 'TextEdit', 'EA_1': 'TextEdit', 'MP_CODE_1': 'TextEdit', 'EA_GTYPE_C': 'TextEdit', 'EA_TYPE_C': 'TextEdit', 'MN_CODE_1': 'TextEdit', 'DC_MN_C_1': 'TextEdit', });
lyr_LPOs_Supervisors_Cape_Metro_3.set('fieldImages', {'No': 'TextEdit', 'First_Name': 'TextEdit', 'Surname': 'TextEdit', 'Gender': 'TextEdit', 'ID_Number': 'TextEdit', 'District': 'TextEdit', 'Province': 'TextEdit', 'Position': 'TextEdit', 'Address': 'TextEdit', 'Contact_no': 'TextEdit', 'Latitude': 'TextEdit', 'Longitude': 'TextEdit', 'Latitude_D': 'TextEdit', 'Longitude_': 'TextEdit', });
lyr_Metro_Split_Final_4.set('fieldImages', {'OBJECTID': 'Range', 'DISTRICT': 'TextEdit', 'DC_NAME': 'TextEdit', 'Office': 'TextEdit', });
lyr_Linked_PSU_EA_Metro1_1.set('fieldLabels', {'OBJECTID': 'no label', 'PSU_NO_M': 'inline label - always visible', 'EA_CODE': 'no label', 'EA_GTYPE': 'no label', 'EA_TYPE': 'no label', 'SUB_EA_NR': 'no label', 'SUB_EA_COD': 'no label', 'SUB_EA_G_T': 'no label', 'SUB_EA_TYP': 'no label', 'DU_COUNT': 'no label', 'DU_STATUS': 'no label', 'FIELDWORKE': 'no label', 'FIELDWOR_1': 'no label', 'SUPERVISOR': 'no label', 'SUPERVIS_1': 'no label', 'FOO_NR': 'no label', 'FOO': 'no label', 'MONITOR_NR': 'no label', 'MONITOR': 'no label', 'ALTERNATE': 'no label', 'EA_2011': 'no label', 'SP_CODE': 'no label', 'SAL_CODE': 'no label', 'GEO_ASSESS': 'no label', 'GEO_POINT_': 'no label', 'FILTER_UPD': 'no label', 'FILTER_PRO': 'no label', 'EDITOR': 'no label', 'EDITOR_STA': 'no label', 'QA_ASSURER': 'no label', 'QA_STATUS': 'no label', 'QA_ASSUR_1': 'no label', 'QA_STATUS2': 'no label', 'created_us': 'no label', 'created_da': 'no label', 'last_edite': 'no label', 'last_edi_1': 'no label', 'SP_NAME': 'no label', 'MP_CODE': 'no label', 'MP_NAME': 'no label', 'MN_MDB_C': 'no label', 'MN_CODE': 'no label', 'MN_NAME': 'no label', 'MN_TYPE': 'no label', 'DC_MDB_C': 'no label', 'DC_MN_C': 'no label', 'DC_NAME': 'no label', 'PR_MDB_C': 'no label', 'PR_CODE': 'no label', 'PR_NAME': 'no label', 'GlobalID': 'no label', 'ESTIMATED_': 'no label', 'OBSERVED_D': 'no label', 'QA_DU_COUN': 'no label', 'MRN_COUNT': 'no label', 'HH_COUNT': 'no label', 'SDI_COUNT': 'no label', 'GATED_COMM': 'no label', 'OTHER': 'no label', 'PSU_STATUS': 'no label', 'COMMENTS': 'no label', 'COMMENTS2': 'no label', 'HH_COUNT_2': 'no label', 'DU_COUNT_2': 'no label', 'EA_COUNT': 'no label', 'MERGED_EA_': 'no label', 'Shape_Leng': 'no label', 'Shape_Area': 'no label', 'EA': 'no label', 'PSUNO': 'no label', 'rotation': 'no label', 'EA_GTYPE_1': 'no label', 'EA_TYPE_1': 'no label', 'SP_CODE_1': 'no label', 'SP_NAME_1': 'no label', 'MP_NAME_1': 'no label', 'MN_NAME_1': 'no label', 'DC_MDB_C_1': 'no label', 'DC_NAME_1': 'no label', 'PR_NAME_1': 'no label', 'PR_CODE_1': 'no label', 'STRATUM': 'no label', 'EA2': 'no label', 'PSU_NO_M_1': 'inline label - always visible', 'EA_1': 'no label', 'MP_CODE_1': 'no label', 'EA_GTYPE_C': 'no label', 'EA_TYPE_C': 'no label', 'MN_CODE_1': 'no label', 'DC_MN_C_1': 'no label', });
lyr_Linked_PSU_EA_Metro2_2.set('fieldLabels', {'OBJECTID': 'no label', 'PSU_NO_M': 'no label', 'EA_CODE': 'no label', 'EA_GTYPE': 'no label', 'EA_TYPE': 'no label', 'SUB_EA_NR': 'no label', 'SUB_EA_COD': 'no label', 'SUB_EA_G_T': 'no label', 'SUB_EA_TYP': 'no label', 'DU_COUNT': 'no label', 'DU_STATUS': 'no label', 'FIELDWORKE': 'no label', 'FIELDWOR_1': 'no label', 'SUPERVISOR': 'no label', 'SUPERVIS_1': 'no label', 'FOO_NR': 'no label', 'FOO': 'no label', 'MONITOR_NR': 'no label', 'MONITOR': 'no label', 'ALTERNATE': 'no label', 'EA_2011': 'no label', 'SP_CODE': 'no label', 'SAL_CODE': 'no label', 'GEO_ASSESS': 'no label', 'GEO_POINT_': 'no label', 'FILTER_UPD': 'no label', 'FILTER_PRO': 'no label', 'EDITOR': 'no label', 'EDITOR_STA': 'no label', 'QA_ASSURER': 'no label', 'QA_STATUS': 'no label', 'QA_ASSUR_1': 'no label', 'QA_STATUS2': 'no label', 'created_us': 'no label', 'created_da': 'no label', 'last_edite': 'no label', 'last_edi_1': 'no label', 'SP_NAME': 'no label', 'MP_CODE': 'no label', 'MP_NAME': 'no label', 'MN_MDB_C': 'no label', 'MN_CODE': 'no label', 'MN_NAME': 'no label', 'MN_TYPE': 'no label', 'DC_MDB_C': 'no label', 'DC_MN_C': 'no label', 'DC_NAME': 'no label', 'PR_MDB_C': 'no label', 'PR_CODE': 'no label', 'PR_NAME': 'no label', 'GlobalID': 'no label', 'ESTIMATED_': 'no label', 'OBSERVED_D': 'no label', 'QA_DU_COUN': 'no label', 'MRN_COUNT': 'no label', 'HH_COUNT': 'no label', 'SDI_COUNT': 'no label', 'GATED_COMM': 'no label', 'OTHER': 'no label', 'PSU_STATUS': 'no label', 'COMMENTS': 'no label', 'COMMENTS2': 'no label', 'HH_COUNT_2': 'no label', 'DU_COUNT_2': 'no label', 'EA_COUNT': 'no label', 'MERGED_EA_': 'no label', 'Shape_Leng': 'no label', 'Shape_Area': 'no label', 'EA': 'no label', 'PSUNO': 'no label', 'rotation': 'no label', 'EA_GTYPE_1': 'no label', 'EA_TYPE_1': 'no label', 'SP_CODE_1': 'no label', 'SP_NAME_1': 'no label', 'MP_NAME_1': 'no label', 'MN_NAME_1': 'no label', 'DC_MDB_C_1': 'no label', 'DC_NAME_1': 'no label', 'PR_NAME_1': 'no label', 'PR_CODE_1': 'no label', 'STRATUM': 'no label', 'EA2': 'no label', 'PSU_NO_M_1': 'no label', 'EA_1': 'no label', 'MP_CODE_1': 'no label', 'EA_GTYPE_C': 'no label', 'EA_TYPE_C': 'no label', 'MN_CODE_1': 'no label', 'DC_MN_C_1': 'no label', });
lyr_LPOs_Supervisors_Cape_Metro_3.set('fieldLabels', {'No': 'no label', 'First_Name': 'no label', 'Surname': 'no label', 'Gender': 'no label', 'ID_Number': 'no label', 'District': 'no label', 'Province': 'no label', 'Position': 'no label', 'Address': 'no label', 'Contact_no': 'no label', 'Latitude': 'no label', 'Longitude': 'no label', 'Latitude_D': 'no label', 'Longitude_': 'no label', });
lyr_Metro_Split_Final_4.set('fieldLabels', {'OBJECTID': 'no label', 'DISTRICT': 'no label', 'DC_NAME': 'no label', 'Office': 'no label', });
lyr_Metro_Split_Final_4.on('precompose', function(evt) {
    evt.context.globalCompositeOperation = 'normal';
});